name: Cypress Tests
on: [workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress
        run: npm install cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # Prevent use of pnpm
          install: false
          build: npm run build
          start: npm start
